import { ChartOfAccount } from "@/lib/types";

export const mockChartOfAccounts: ChartOfAccount[] = [
  // 1000: ASSETS
  // 1100: Cash & Bank Balances
  {
    code: "1110",
    name: "HDFC Bank Current A/c #50200084920194",
    category: "asset",
    subHead: "Bank Accounts",
    parentCode: "1100",
    openingBalance: 6420500,
    currentBalance: 8942300,
    normalBalance: "debit",
    description: "Primary operational bank account at Lower Parel Branch, Mumbai.",
  },
  {
    code: "1120",
    name: "Petty Cash - Bhiwandi Factory Office",
    category: "asset",
    subHead: "Cash-in-Hand",
    parentCode: "1100",
    openingBalance: 45000,
    currentBalance: 38200,
    normalBalance: "debit",
  },
  // 1200: Sundry Debtors / Trade Receivables
  {
    code: "1210",
    name: "Trade Receivables - Domestic B2B",
    category: "asset",
    subHead: "Sundry Debtors",
    parentCode: "1200",
    openingBalance: 4210000,
    currentBalance: 3245600,
    normalBalance: "debit",
    description: "Unpaid invoices from wholesale textile apparel manufacturers.",
  },
  {
    code: "1220",
    name: "Provision for Doubtful Debts",
    category: "asset",
    subHead: "Sundry Debtors",
    parentCode: "1200",
    openingBalance: -150000,
    currentBalance: -150000,
    normalBalance: "credit",
  },
  // 1300: Inventories
  {
    code: "1310",
    name: "Raw Materials Inventory (Yarn & Fibre Bales)",
    category: "asset",
    subHead: "Inventories",
    parentCode: "1300",
    openingBalance: 1850000,
    currentBalance: 2140000,
    normalBalance: "debit",
  },
  {
    code: "1320",
    name: "Work-in-Progress (Weaving & Sizing)",
    category: "asset",
    subHead: "Inventories",
    parentCode: "1300",
    openingBalance: 920000,
    currentBalance: 1105000,
    normalBalance: "debit",
  },
  {
    code: "1330",
    name: "Finished Goods Inventory (Grey & Finished Fabrics)",
    category: "asset",
    subHead: "Inventories",
    parentCode: "1300",
    openingBalance: 2450000,
    currentBalance: 2890000,
    normalBalance: "debit",
  },
  // 1400: GST Input Tax Credit (ITC) Receivables
  {
    code: "1410",
    name: "Input CGST Receivable",
    category: "asset",
    subHead: "Duties & Taxes (Input)",
    parentCode: "1400",
    openingBalance: 340000,
    currentBalance: 485200,
    normalBalance: "debit",
  },
  {
    code: "1420",
    name: "Input SGST Receivable",
    category: "asset",
    subHead: "Duties & Taxes (Input)",
    parentCode: "1400",
    openingBalance: 340000,
    currentBalance: 485200,
    normalBalance: "debit",
  },
  {
    code: "1430",
    name: "Input IGST Receivable",
    category: "asset",
    subHead: "Duties & Taxes (Input)",
    parentCode: "1400",
    openingBalance: 380000,
    currentBalance: 459400,
    normalBalance: "debit",
  },
  // 1500: Property, Plant & Equipment (Fixed Assets)
  {
    code: "1510",
    name: "Plant & Machinery - Rapier Looms & Sizing Units",
    category: "asset",
    subHead: "Tangible Fixed Assets",
    parentCode: "1500",
    openingBalance: 14500000,
    currentBalance: 14500000,
    normalBalance: "debit",
  },
  {
    code: "1520",
    name: "Accumulated Depreciation - Plant & Machinery",
    category: "asset",
    subHead: "Tangible Fixed Assets",
    parentCode: "1500",
    openingBalance: -3200000,
    currentBalance: -3650000,
    normalBalance: "credit",
  },

  // 2000: LIABILITIES
  // 2100: Sundry Creditors / Trade Payables
  {
    code: "2110",
    name: "Trade Payables - Raw Material Suppliers",
    category: "liability",
    subHead: "Sundry Creditors",
    parentCode: "2100",
    openingBalance: 1850000,
    currentBalance: 1248000,
    normalBalance: "credit",
  },
  {
    code: "2120",
    name: "Trade Payables - Service & Freight Vendors",
    category: "liability",
    subHead: "Sundry Creditors",
    parentCode: "2100",
    openingBalance: 310000,
    currentBalance: 245000,
    normalBalance: "credit",
  },
  // 2200: GST Output Tax Payable
  {
    code: "2210",
    name: "Output CGST Payable",
    category: "liability",
    subHead: "Duties & Taxes (Output)",
    parentCode: "2200",
    openingBalance: 280000,
    currentBalance: 342100,
    normalBalance: "credit",
  },
  {
    code: "2220",
    name: "Output SGST Payable",
    category: "liability",
    subHead: "Duties & Taxes (Output)",
    parentCode: "2200",
    openingBalance: 280000,
    currentBalance: 342100,
    normalBalance: "credit",
  },
  {
    code: "2230",
    name: "Output IGST Payable",
    category: "liability",
    subHead: "Duties & Taxes (Output)",
    parentCode: "2200",
    openingBalance: 410000,
    currentBalance: 512400,
    normalBalance: "credit",
  },
  // 2300: TDS & Statutory Dues Payable
  {
    code: "2310",
    name: "TDS Payable (Sec 194C - Contractors)",
    category: "liability",
    subHead: "Statutory Dues",
    parentCode: "2300",
    openingBalance: 12400,
    currentBalance: 16800,
    normalBalance: "credit",
  },
  {
    code: "2320",
    name: "TDS Payable (Sec 194J - Professional)",
    category: "liability",
    subHead: "Statutory Dues",
    parentCode: "2300",
    openingBalance: 6000,
    currentBalance: 12000,
    normalBalance: "credit",
  },
  {
    code: "2330",
    name: "Salaries & Wages Payable",
    category: "liability",
    subHead: "Provisions",
    parentCode: "2300",
    openingBalance: 520000,
    currentBalance: 480000,
    normalBalance: "credit",
  },
  // 2500: Borrowings
  {
    code: "2510",
    name: "HDFC Bank Term Loan (Machinery Refinance)",
    category: "liability",
    subHead: "Long-Term Borrowings",
    parentCode: "2500",
    openingBalance: 4500000,
    currentBalance: 3950000,
    normalBalance: "credit",
  },

  // 3000: EQUITY
  {
    code: "3110",
    name: "Paid-up Equity Share Capital",
    category: "equity",
    subHead: "Share Capital",
    parentCode: "3000",
    openingBalance: 5000000,
    currentBalance: 5000000,
    normalBalance: "credit",
  },
  {
    code: "3210",
    name: "Retained Earnings / General Reserves",
    category: "equity",
    subHead: "Reserves & Surplus",
    parentCode: "3000",
    openingBalance: 14200000,
    currentBalance: 17450000,
    normalBalance: "credit",
  },

  // 4000: INCOME / REVENUE
  {
    code: "4110",
    name: "Sales of Finished Fabrics - Domestic",
    category: "income",
    subHead: "Operating Revenue",
    parentCode: "4000",
    openingBalance: 0,
    currentBalance: 18450000,
    normalBalance: "credit",
  },
  {
    code: "4120",
    name: "Sales of Grey / Greige Cloth",
    category: "income",
    subHead: "Operating Revenue",
    parentCode: "4000",
    openingBalance: 0,
    currentBalance: 6820000,
    normalBalance: "credit",
  },
  {
    code: "4210",
    name: "Interest on Auto-Sweep Bank Deposits",
    category: "income",
    subHead: "Other Income",
    parentCode: "4000",
    openingBalance: 0,
    currentBalance: 42500,
    normalBalance: "credit",
  },

  // 5000: DIRECT EXPENSES / COGS
  {
    code: "5110",
    name: "Cotton Yarn & Raw Material Purchases",
    category: "expense",
    subHead: "Cost of Materials Consumed",
    parentCode: "5000",
    openingBalance: 0,
    currentBalance: 9840000,
    normalBalance: "debit",
  },
  {
    code: "5120",
    name: "Dyes & Processing Chemicals",
    category: "expense",
    subHead: "Direct Production Costs",
    parentCode: "5000",
    openingBalance: 0,
    currentBalance: 1640000,
    normalBalance: "debit",
  },
  {
    code: "5130",
    name: "Factory Power & Fuel Charges (Torrent Power)",
    category: "expense",
    subHead: "Direct Production Costs",
    parentCode: "5000",
    openingBalance: 0,
    currentBalance: 1140000,
    normalBalance: "debit",
  },
  {
    code: "5140",
    name: "Factory Wages & Loom Operators",
    category: "expense",
    subHead: "Direct Labour",
    parentCode: "5000",
    openingBalance: 0,
    currentBalance: 2450000,
    normalBalance: "debit",
  },

  // 6000: INDIRECT / ADMINISTRATIVE EXPENSES
  {
    code: "6110",
    name: "Administrative Salaries & Management Remuneration",
    category: "expense",
    subHead: "Employee Benefit Expense",
    parentCode: "6000",
    openingBalance: 0,
    currentBalance: 1850000,
    normalBalance: "debit",
  },
  {
    code: "6210",
    name: "Freight Outward & Logistics (Blue Dart / TCI)",
    category: "expense",
    subHead: "Selling & Distribution",
    parentCode: "6000",
    openingBalance: 0,
    currentBalance: 485000,
    normalBalance: "debit",
  },
  {
    code: "6310",
    name: "Cloud Hosting & Software Licenses (AWS / Zoho)",
    category: "expense",
    subHead: "Administrative Expenses",
    parentCode: "6000",
    openingBalance: 0,
    currentBalance: 245000,
    normalBalance: "debit",
  },
  {
    code: "6410",
    name: "Legal, Tax Advisory & Audit Fees",
    category: "expense",
    subHead: "Professional Charges",
    parentCode: "6000",
    openingBalance: 0,
    currentBalance: 180000,
    normalBalance: "debit",
  },
  {
    code: "6510",
    name: "Bank Charges & Forex Hedging Fees",
    category: "expense",
    subHead: "Financial Expenses",
    parentCode: "6000",
    openingBalance: 0,
    currentBalance: 42100,
    normalBalance: "debit",
  },
];
