import {
  TODScheme,
  TODCreditNote,
  TODSettlementPeriod,
  TODAuditLog,
} from "@/lib/types";

export const mockTODSchemes: TODScheme[] = [
  // Scenario A: ABC Metals (Active scheme, 78.5% complete)
  {
    id: "tod-scheme-001",
    customerId: "cust-abc-01",
    customerName: "ABC Metals",
    customerGstin: "27AAACA9921D1ZZ",
    schemeName: "FY 2026-27 Volume Scheme",
    startDate: "2026-04-01",
    endDate: "2027-03-31",
    todType: "quantity",
    target: 10000,
    targetUnit: "MT",
    todRate: 10,
    todRateType: "per_unit",
    settlementFrequency: "annual",
    eligibleProducts: ["All Products", "Hot Rolled Coils (HRC)", "Steel Rebars (Fe 550D)"],
    status: "active",
    notes: "Agreed ₹10/MT commercial volume rebate on achieving 10,000 MT cumulative purchases in FY27.",
    createdAt: "2026-04-01 10:00",
    createdBy: "Aditya Sharma (Commercial Head)",
  },

  // Scenario B: PQR Engineering (Active scheme, 92% complete)
  {
    id: "tod-scheme-002",
    customerId: "cust-pqr-02",
    customerName: "PQR Engineering",
    customerGstin: "24AABCP4412E1ZQ",
    schemeName: "Q2 Specialized Heavy Forging Rebate",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    todType: "quantity",
    target: 5000,
    targetUnit: "MT",
    todRate: 15,
    todRateType: "per_unit",
    settlementFrequency: "quarterly",
    eligibleProducts: ["Heavy Forging Billets", "Carbon Steel Rounds"],
    status: "active",
    notes: "Specialized forging grade rebate @ ₹15/MT for 5,000 MT quarterly commitment.",
    createdAt: "2026-07-01 11:30",
    createdBy: "Neha Gupta (Key Account Manager)",
  },

  // Scenario C: Sharma Auto Components (Target Achieved, Credit Note Pending Approval)
  {
    id: "tod-scheme-003",
    customerId: "cust-sharma-03",
    customerName: "Sharma Auto Components",
    customerGstin: "07AAACS7841B1Z3",
    schemeName: "Automotive Precision Bar Scheme",
    startDate: "2026-04-01",
    endDate: "2026-09-30",
    todType: "quantity",
    target: 8000,
    targetUnit: "MT",
    todRate: 12,
    todRateType: "per_unit",
    settlementFrequency: "half_yearly",
    eligibleProducts: ["Precision Alloy Bright Bars", "Case Hardening Steel"],
    status: "target_achieved",
    notes: "Achieved 8,200 MT. Target exceeded. Credit Note generated and currently awaiting CFO approval.",
    createdAt: "2026-04-02 09:15",
    createdBy: "Aditya Sharma (Commercial Head)",
  },

  // Scenario D: XYZ Industries (Turnover-based, Target Achieved & Settled)
  {
    id: "tod-scheme-004",
    customerId: "cust-xyz-04",
    customerName: "XYZ Industries",
    customerGstin: "29AABCX1109P1Z8",
    schemeName: "Turnover Growth Incentive Scheme FY27",
    startDate: "2026-04-01",
    endDate: "2027-03-31",
    todType: "turnover",
    target: 50000000, // ₹5.00 Crores
    targetUnit: "INR",
    todRate: 2, // 2% turnover rebate
    todRateType: "percentage",
    settlementFrequency: "on_target_achievement",
    eligibleProducts: ["All Products"],
    status: "settled",
    notes: "Achieved ₹5.40 Crores turnover. 2% TOD credit note of ₹10,80,000 approved and posted to customer ledger.",
    createdAt: "2026-04-05 14:00",
    createdBy: "Aditya Sharma (Commercial Head)",
  },

  // Scenario E: National Steel Works (Expired scheme)
  {
    id: "tod-scheme-005",
    customerId: "cust-nsw-05",
    customerName: "National Steel Works",
    customerGstin: "03AAACN9120M1ZO",
    schemeName: "FY 2025-26 Annual Bulk Volume Rebate",
    startDate: "2025-04-01",
    endDate: "2026-03-31",
    todType: "quantity",
    target: 15000,
    targetUnit: "MT",
    todRate: 8,
    todRateType: "per_unit",
    settlementFrequency: "annual",
    eligibleProducts: ["Structural Steel Beams", "Angles"],
    status: "expired",
    notes: "Customer achieved 6,200 MT against 15,000 MT target before scheme expired on 31st March 2026. Target unfulfilled.",
    createdAt: "2025-04-01 10:00",
    createdBy: "Vikram Malhotra (Regional Director)",
  },

  // Scenario F - Scheme 1: Bharat Forge & Precision (Q1 High-Tensile Wire - Settled)
  {
    id: "tod-scheme-006-A",
    customerId: "cust-bfp-06",
    customerName: "Bharat Forge & Precision",
    customerGstin: "27AABCB3390F1ZX",
    schemeName: "Q1 High-Tensile Wire Commitment",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    todType: "quantity",
    target: 2000,
    targetUnit: "MT",
    todRate: 20,
    todRateType: "per_unit",
    settlementFrequency: "quarterly",
    eligibleProducts: ["High-Tensile Wire Rods"],
    status: "settled",
    notes: "Q1 commitment target satisfied. ₹40,000 credit note issued and settled in July 2026.",
    createdAt: "2026-04-01 09:30",
    createdBy: "Aditya Sharma (Commercial Head)",
  },

  // Scenario F - Scheme 2: Bharat Forge & Precision (FY27 Alloy Billets - Active)
  {
    id: "tod-scheme-006-B",
    customerId: "cust-bfp-06",
    customerName: "Bharat Forge & Precision",
    customerGstin: "27AABCB3390F1ZX",
    schemeName: "FY 2026-27 Alloy Billets Long-Term Scheme",
    startDate: "2026-04-01",
    endDate: "2027-03-31",
    todType: "quantity",
    target: 6000,
    targetUnit: "MT",
    todRate: 14,
    todRateType: "per_unit",
    settlementFrequency: "annual",
    eligibleProducts: ["Alloy Steel Billets", "Special Forging Blooms"],
    status: "active",
    notes: "Active annual program running concurrently alongside specialized quarterly wire agreements.",
    createdAt: "2026-04-10 11:00",
    createdBy: "Aditya Sharma (Commercial Head)",
  },
];

export const mockTODCreditNotes: TODCreditNote[] = [
  // Settled Credit Note for XYZ Industries (Scenario D)
  {
    id: "cn-tod-2026-001",
    creditNoteNumber: "CN-TOD-2026-001",
    schemeId: "tod-scheme-004",
    schemeName: "Turnover Growth Incentive Scheme FY27",
    customerId: "cust-xyz-04",
    customerName: "XYZ Industries",
    qualifyingQuantity: 77142,
    qualifyingTurnover: 54000000, // ₹5.4 Cr
    todRateDescription: "2% turnover incentive discount",
    grossTodAmount: 1080000, // ₹10.8 Lakhs
    gstRate: 0,
    gstAmount: 0,
    totalCreditNoteAmount: 1080000,
    linkedInvoiceIds: ["inv-xyz-001", "inv-xyz-002", "inv-xyz-003", "inv-xyz-004"],
    linkedInvoiceNumbers: ["INV/2026-27/XYZ-01", "INV/2026-27/XYZ-02", "INV/2026-27/XYZ-03", "INV/2026-27/XYZ-04"],
    status: "approved",
    requestedDate: "2026-08-10",
    requestedBy: "Aditya Sharma (Commercial Head)",
    approvedDate: "2026-08-12",
    approvedBy: "Rajesh Verma (CFO)",
    notes: "Turnover target of ₹5.00 Cr surpassed (Achieved: ₹5.40 Cr). Approved 2% commercial credit note.",
  },

  // Settled Credit Note for Bharat Forge Q1 (Scenario F)
  {
    id: "cn-tod-2026-002",
    creditNoteNumber: "CN-TOD-2026-002",
    schemeId: "tod-scheme-006-A",
    schemeName: "Q1 High-Tensile Wire Commitment",
    customerId: "cust-bfp-06",
    customerName: "Bharat Forge & Precision",
    qualifyingQuantity: 2000,
    qualifyingTurnover: 14000000,
    todRateDescription: "₹20 per MT volume rebate",
    grossTodAmount: 40000,
    gstRate: 0,
    gstAmount: 0,
    totalCreditNoteAmount: 40000,
    linkedInvoiceIds: ["inv-bfp-001", "inv-bfp-002"],
    linkedInvoiceNumbers: ["INV/2026-27/BFP-01", "INV/2026-27/BFP-02"],
    status: "approved",
    requestedDate: "2026-07-04",
    requestedBy: "Neha Gupta (Key Account Manager)",
    approvedDate: "2026-07-06",
    approvedBy: "Rajesh Verma (CFO)",
    notes: "Q1 target of 2,000 MT fulfilled. Commercial credit note adjusted against July invoices.",
  },

  // Pending Approval Credit Note for Sharma Auto Components (Scenario C)
  {
    id: "cn-tod-2026-003",
    creditNoteNumber: "CN-TOD-2026-003",
    schemeId: "tod-scheme-003",
    schemeName: "Automotive Precision Bar Scheme",
    customerId: "cust-sharma-03",
    customerName: "Sharma Auto Components",
    qualifyingQuantity: 8200,
    qualifyingTurnover: 65600000,
    todRateDescription: "₹12 per MT volume rebate",
    grossTodAmount: 98400,
    gstRate: 0,
    gstAmount: 0,
    totalCreditNoteAmount: 98400,
    linkedInvoiceIds: ["inv-sac-001", "inv-sac-002", "inv-sac-003"],
    linkedInvoiceNumbers: ["INV/2026-27/SAC-01", "INV/2026-27/SAC-02", "INV/2026-27/SAC-03"],
    status: "pending_approval",
    requestedDate: "2026-08-24",
    requestedBy: "Aditya Sharma (Commercial Head)",
    notes: "Target of 8,000 MT achieved (Current: 8,200 MT). Credit note drafted, awaiting CFO authorization.",
  },
];

export const mockTODSettlementPeriods: Record<string, TODSettlementPeriod[]> = {
  "tod-scheme-001": [
    {
      id: "sp-abc-q1",
      periodLabel: "Q1 (Apr–Jun 2026)",
      qualifyingQty: 3500,
      qualifyingValue: 2450000,
      todAmount: 35000,
      settledAmount: 0,
      status: "pending",
    },
    {
      id: "sp-abc-q2",
      periodLabel: "Q2 (Jul–Sep 2026)",
      qualifyingQty: 4350,
      qualifyingValue: 3045000,
      todAmount: 43500,
      settledAmount: 0,
      status: "pending",
    },
    {
      id: "sp-abc-q3",
      periodLabel: "Q3 (Oct–Dec 2026)",
      qualifyingQty: 0,
      qualifyingValue: 0,
      todAmount: 0,
      settledAmount: 0,
      status: "pending",
    },
    {
      id: "sp-abc-q4",
      periodLabel: "Q4 (Jan–Mar 2027)",
      qualifyingQty: 0,
      qualifyingValue: 0,
      todAmount: 0,
      settledAmount: 0,
      status: "pending",
    },
  ],
};

export const mockTODAuditLogs: TODAuditLog[] = [
  {
    id: "audit-101",
    schemeId: "tod-scheme-001",
    timestamp: "2026-04-01 10:00",
    userId: "usr-sales-01",
    userName: "Aditya Sharma (Commercial Head)",
    action: "SCHEME_CREATED",
    details: "Created FY 2026-27 Volume Scheme for ABC Metals. Target: 10,000 MT @ ₹10/MT rebate.",
  },
  {
    id: "audit-102",
    schemeId: "tod-scheme-001",
    timestamp: "2026-05-12 14:20",
    userId: "usr-billing-02",
    userName: "System Automation",
    action: "INVOICE_QUALIFIED",
    details: "Invoice INV-1021 qualified for 1,500 MT (Potential TOD: ₹15,000).",
  },
  {
    id: "audit-103",
    schemeId: "tod-scheme-001",
    timestamp: "2026-06-25 16:10",
    userId: "usr-billing-02",
    userName: "System Automation",
    action: "INVOICE_QUALIFIED",
    details: "Invoice INV-1048 qualified for 2,000 MT (Potential TOD: ₹20,000).",
  },
  {
    id: "audit-104",
    schemeId: "tod-scheme-001",
    timestamp: "2026-07-28 11:45",
    userId: "usr-billing-02",
    userName: "System Automation",
    action: "INVOICE_QUALIFIED",
    details: "Invoice INV-1087 qualified for 3,000 MT (Potential TOD: ₹30,000).",
  },
  {
    id: "audit-105",
    schemeId: "tod-scheme-001",
    timestamp: "2026-08-20 18:00",
    userId: "usr-billing-02",
    userName: "System Automation",
    action: "INVOICE_QUALIFIED",
    details: "Invoice INV-1124 qualified for 1,350 MT (Cumulative Achieved: 7,850 MT).",
  },
  {
    id: "audit-106",
    schemeId: "tod-scheme-004",
    timestamp: "2026-08-12 16:00",
    userId: "usr-cfo-01",
    userName: "Rajesh Verma (CFO)",
    action: "CREDIT_NOTE_POSTED",
    details: "Approved & posted CN-TOD-2026-001 (₹10,80,000) for XYZ Industries. Receivables reduced.",
  },
];
